Pandas Example

In [1]:
 l=[1,2, 4, 5,67]
l

[1, 2, 4, 5, 67]

In [2]:
import numpy as np
import pandas as pd

In [3]:
l=[1,2, 4, 5,67]
l

[1, 2, 4, 5, 67]

In [5]:
c= np.array(l)

In [6]:
c

array([ 1,  2,  4,  5, 67])

In [7]:
d= pd.Series(l)
d

0     1
1     2
2     4
3     5
4    67
dtype: int64

In [10]:
d+10

0    11
1    12
2    14
3    15
4    77
dtype: int64

In [11]:
c+10

array([11, 12, 14, 15, 77])

In [14]:
d= pd.Series(l, index=['a','b','c','d','e'])
d

a     1
b     2
c     4
d     5
e    67
dtype: int64

In [16]:
d= pd.Series(l, index=range(len(l)))
d

0     1
1     2
2     4
3     5
4    67
dtype: int64

In [17]:
g= {'a': 123, 'b':345, 'c':657}
g

{'a': 123, 'b': 345, 'c': 657}

In [18]:
f=pd.Series(g)
f

a    123
b    345
c    657
dtype: int64

In [8]:
h= {'a': [123], 'b':[345], 'c':[657]}
j= pd.DataFrame(h)
j

,a,b,c
0,123,345,657


In [9]:
h= {'a': 123, 'b':345, 'c':657}
j= pd.DataFrame(h, index=[0])
j

,a,b,c
0,123,345,657


In [13]:
print(pd.DataFrame([[12, 34, 56, 78],[43, 65, 76,87]], columns=['a','b','c','d'], index=['r1','r2']))

     a   b   c   d
r1  12  34  56  78
r2  43  65  76  87


#Create dataframe using 2D array

In [15]:
ar_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(ar_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
df1=pd.DataFrame(ar_2d, columns=['a','b','c','d'])
df1['serial_no']=np.arange(16,18)
df1.set_index('serial_no')

,a,b,c,d
serial_no,,,,
16,1,2,3,4
17,5,6,7,8


# df

In [17]:
df1.shape

(2, 5)

In [18]:
type(df1)

pandas.core.frame.DataFrame

In [19]:
type(ar_2d)

numpy.ndarray

In [20]:
df = pd.DataFrame({'Age':[25,23,56,86,78,98], 'Salary':[120000, 145000, 856300, 564688, 632363, 756214], 'Gender':['M','F','F','M','M','F']})
df

,Age,Salary,Gender
0,25,120000,M
1,23,145000,F
2,56,856300,F
3,86,564688,M
4,78,632363,M
5,98,756214,F


In [21]:
df.set_index('Gender', inplace=True)
df

,Age,Salary
Gender,,
M,25,120000
F,23,145000
F,56,856300
M,86,564688
M,78,632363
F,98,756214


In [22]:
df.loc['M']

,Age,Salary
Gender,,
M,25,120000
M,86,564688
M,78,632363


**Selecting/extracting data**

In [24]:
df = pd.DataFrame({'Age':[25,23,56,86,78,98], 'Salary':[120000, 145000, 856300, 564688, 632363, 756214], 'Gender':['M','F','F','M','M','F']})
df

,Age,Salary,Gender
0,25,120000,M
1,23,145000,F
2,56,856300,F
3,86,564688,M
4,78,632363,M
5,98,756214,F


In [25]:
df.loc[2]

Age           56
Salary    856300
Gender         F
Name: 2, dtype: object

**selction based on slicing**

In [27]:
df.loc[0:4:2]

,Age,Salary,Gender
0,25,120000,M
2,56,856300,F
4,78,632363,M


**selction w/o slicing**

In [77]:
df.loc[[0, 2, 4]]

,Age,Salary,Gender
0,25,120000,M
2,56,856300,F
4,78,632363,M


**extract single column**

In [28]:
df.loc[:,'Salary']

0    120000
1    145000
2    856300
3    564688
4    632363
5    756214
Name: Salary, dtype: int64

**extract multiple columns with/without slicing**

In [32]:
df.loc[:,'Age':'Gender']

,Age,Salary,Gender
0,25,120000,M
1,23,145000,F
2,56,856300,F
3,86,564688,M
4,78,632363,M
5,98,756214,F


In [33]:
df.loc[:,['Age','Gender']]

,Age,Gender
0,25,M
1,23,F
2,56,F
3,86,M
4,78,M
5,98,F


**extract selected rows and selected columns**

In [34]:
df.loc[4,['Age','Gender']]

Age       78
Gender     M
Name: 4, dtype: object

**USE OF iLOC**

In [35]:
df

,Age,Salary,Gender
0,25,120000,M
1,23,145000,F
2,56,856300,F
3,86,564688,M
4,78,632363,M
5,98,756214,F


In [36]:
df.iloc[-1:-3,:]

,Age,Salary,Gender


**reset index**


In [37]:
df.set_index('Gender', inplace=True)

In [95]:
df

,Age,Salary
Gender,,
M,25,120000
F,23,145000
F,56,856300
M,86,564688
M,78,632363
F,98,756214


In [38]:
df.reset_index()

,Gender,Age,Salary
0,M,25,120000
1,F,23,145000
2,F,56,856300
3,M,86,564688
4,M,78,632363
5,F,98,756214


**drop single row**

In [39]:
df= df.drop(index=['M'])
df

,Age,Salary
Gender,,
F,23,145000
F,56,856300
F,98,756214


In [40]:
df = pd.DataFrame({'Age':[25,23,56,86,78,98], 'Salary':[120000, 145000, 856300, 564688, 632363, 756214], 'Gender':['M','F','F','M','M','F']})
df

,Age,Salary,Gender
0,25,120000,M
1,23,145000,F
2,56,856300,F
3,86,564688,M
4,78,632363,M
5,98,756214,F


In [41]:
df=df.drop(index=[2,3])
df

,Age,Salary,Gender
0,25,120000,M
1,23,145000,F
4,78,632363,M
5,98,756214,F


In [117]:
df

,Age,Salary,Gender
0,25,120000,M
1,23,145000,F
4,78,632363,M
5,98,756214,F


In [42]:
df=df.drop([1])

In [43]:
df

,Age,Salary,Gender
0,25,120000,M
4,78,632363,M
5,98,756214,F


In [46]:
df=df.drop(index=range(0,5))
df

,Age,Salary,Gender
5,98,756214,F


In [127]:
df

,Age,Salary,Gender
0,25,120000,M
4,78,632363,M
5,98,756214,F


In [47]:
df = pd.DataFrame({'Age':[25,23,56,86,78,98], 'Salary':[120000, 145000, 856300, 564688, 632363, 756214], 'Gender':['M','F','F','M','M','F']})
df

,Age,Salary,Gender
0,25,120000,M
1,23,145000,F
2,56,856300,F
3,86,564688,M
4,78,632363,M
5,98,756214,F


In [48]:
df= df.drop(index=range(2,5))
df

,Age,Salary,Gender
0,25,120000,M
1,23,145000,F
5,98,756214,F


In [55]:
 df = pd.DataFrame({'Age':[25,23,56,86,78,98], 'Salary':[120000, 145000, 856300, 564688, 632363, 756214], 'Gender':['M','F','F','M','M','F']})
df

,Age,Salary,Gender
0,25,120000,M
1,23,145000,F
2,56,856300,F
3,86,564688,M
4,78,632363,M
5,98,756214,F


**drop a column**

In [50]:
df.drop(columns='Age', inplace = True)

In [51]:
df

,Salary,Gender
0,120000,M
1,145000,F
2,856300,F
3,564688,M
4,632363,M
5,756214,F


In [52]:
df.drop(columns=['Salary','Gender'], inplace=True)

In [53]:
df

""
0
1
2
3
4
5


**sort values**

In [56]:
df.sort_values(by='Age')

,Age,Salary,Gender
1,23,145000,F
0,25,120000,M
2,56,856300,F
4,78,632363,M
3,86,564688,M
5,98,756214,F


In [57]:
#sorting in descending order
df.sort_values(by='Age', ascending=False)

,Age,Salary,Gender
5,98,756214,F
3,86,564688,M
4,78,632363,M
2,56,856300,F
0,25,120000,M
1,23,145000,F


**Combing Dataframes**

In [58]:
df1=pd.DataFrame({'City':['Mumbai','Delhi','Banglore','Hydrabad'], 'Temperature':[32,45,40,36]})
df1

,City,Temperature
0,Mumbai,32
1,Delhi,45
2,Banglore,40
3,Hydrabad,36


In [59]:
df2=pd.DataFrame({'City':['Delhi','Mumbai','Banglore','Chennai'], 'Humidity':[68,65,75,70]})
df2

,City,Humidity
0,Delhi,68
1,Mumbai,65
2,Banglore,75
3,Chennai,70


**Concatanation**

In [160]:
df3=pd.concat([df1,df2], axis=1)

In [161]:
df3

,City,Temperature,City,Humidity
0,Mumbai,32,Delhi,68
1,Delhi,45,Mumbai,65
2,Banglore,40,Banglore,75
3,Hydrabad,36,Chennai,70


In [60]:
df4=pd.concat([df1,df2],axis=0, ignore_index=True)
df4

,City,Temperature,Humidity
0,Mumbai,32.0,NaN
1,Delhi,45.0,NaN
2,Banglore,40.0,NaN
3,Hydrabad,36.0,NaN
4,Delhi,NaN,68.0
5,Mumbai,NaN,65.0
6,Banglore,NaN,75.0
7,Chennai,NaN,70.0


**Merging of Dataframes**

In [62]:
pd.merge(df1,df2, on='City', how='outer')

,City,Temperature,Humidity
0,Banglore,40.0,75.0
1,Chennai,NaN,70.0
2,Delhi,45.0,68.0
3,Hydrabad,36.0,NaN
4,Mumbai,32.0,65.0


**display full data**

In [78]:
## use of display.max_rows
import pandas as pd
df=pd.read_csv('C:\\Users\\yadav\\Downloads\\Jupyter\\Datasets\\imdb_top_1000.csv')
df.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"2,83,41,469"
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"13,49,66,411"
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"53,48,58,444"
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"5,73,00,000"
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"43,60,000"


In [76]:
pd.set_option('display.max_rows', None)

In [77]:
df

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"2,83,41,469"
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"13,49,66,411"
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"53,48,58,444"
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"5,73,00,000"
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"43,60,000"
5,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"37,78,45,905"
6,Pulp Fiction,1994,A,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",94.0,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,1826188,"10,79,28,762"
7,Schindler's List,1993,A,195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"9,68,98,818"
8,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,"29,25,76,195"
9,Fight Club,1999,A,139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,66.0,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,1854740,"3,70,30,102"


In [79]:
df1=pd.read_excel('C:\\Users\\yadav\\Downloads\\Jupyter\\Datasets\\tips_data.xlsx')
df1

,total_bill,tip,sex,smoker,day,time,size
0,21.85,9.73,Male,No,Thur,Dinner,4
1,47.78,7.98,Female,Yes,Thur,Lunch,3
2,37.94,9.46,Male,No,Sat,Lunch,1
3,31.94,9.05,Male,Yes,Fri,Dinner,4
4,12.02,6.38,Female,Yes,Fri,Dinner,6
5,12.02,9.30,Male,Yes,Thur,Lunch,4
6,7.61,1.80,Female,Yes,Sun,Dinner,6
7,43.98,2.76,Female,No,Fri,Dinner,3
8,32.05,1.41,Female,No,Sun,Lunch,6
9,36.86,3.93,Male,Yes,Fri,Lunch,1


In [10]:
## use of shape, size, columns, keys
df1.shape

(50, 7)

In [11]:
df1.size

350

In [81]:
df1.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [14]:
df1.keys()

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

**Rename Column**

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  50 non-null     float64
 1   tip         50 non-null     float64
 2   sex         50 non-null     object 
 3   smoker      50 non-null     object 
 4   day         50 non-null     object 
 5   time        50 non-null     object 
 6   size        50 non-null     int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 2.9+ KB


In [17]:
# use of rename
df1=df1.rename(columns={'sex':'gender','size':'no_of_members'})
df1.keys()

Index(['total_bill', 'tip', 'gender', 'smoker', 'day', 'time',
       'no_of_members'],
      dtype='object')

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   total_bill     50 non-null     float64
 1   tip            50 non-null     float64
 2   gender         50 non-null     object 
 3   smoker         50 non-null     object 
 4   day            50 non-null     object 
 5   time           50 non-null     object 
 6   no_of_members  50 non-null     int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 2.9+ KB


**data types of each columns**

In [21]:
df1.dtypes

total_bill       float64
tip              float64
gender            object
smoker            object
day               object
time              object
no_of_members      int64
dtype: object

**check for missing values**

In [26]:
df1.isnull().sum()

total_bill       0
tip              0
gender           0
smoker           0
day              0
time             0
no_of_members    0
dtype: int64

**Extracting/Accessing values**

In [28]:
df1.iloc[[2,3,4],[0,2]]

,total_bill,gender
2,37.94,Male
3,31.94,Male
4,12.02,Female


In [30]:
import numpy as np
df=pd.DataFrame({'X':[1,2,3,np.nan,5]})
df

,X
0,1.0
1,2.0
2,3.0
3,NaN
4,5.0


In [32]:
df.isnull().sum()

X    1
dtype: int64

In [33]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   total_bill     50 non-null     float64
 1   tip            50 non-null     float64
 2   gender         50 non-null     object 
 3   smoker         50 non-null     object 
 4   day            50 non-null     object 
 5   time           50 non-null     object 
 6   no_of_members  50 non-null     int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 2.9+ KB


In [37]:
df1['gender']

0       Male
1     Female
2       Male
3       Male
4     Female
5       Male
6     Female
7     Female
8     Female
9       Male
10      Male
11      Male
12      Male
13      Male
14      Male
15      Male
16    Female
17      Male
18    Female
19      Male
20      Male
21      Male
22    Female
23    Female
24    Female
25    Female
26      Male
27    Female
28      Male
29      Male
30    Female
31    Female
32    Female
33    Female
34    Female
35    Female
36    Female
37    Female
38      Male
39    Female
40    Female
41      Male
42    Female
43      Male
44      Male
45    Female
46      Male
47      Male
48      Male
49      Male
Name: gender, dtype: object

In [38]:
df1['gender'].shape

(50,)

In [39]:
df1['gender'].size

50

In [40]:
df1['gender'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 50 entries, 0 to 49
Series name: gender
Non-Null Count  Dtype 
--------------  ----- 
50 non-null     object
dtypes: object(1)
memory usage: 532.0+ bytes


**ACCESS OF DATA OF MULTIPLE COLUMNS**

In [41]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   total_bill     50 non-null     float64
 1   tip            50 non-null     float64
 2   gender         50 non-null     object 
 3   smoker         50 non-null     object 
 4   day            50 non-null     object 
 5   time           50 non-null     object 
 6   no_of_members  50 non-null     int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 2.9+ KB


In [44]:
df1[['tip','smoker','time']]

,tip,smoker,time
0,9.73,No,Dinner
1,7.98,Yes,Lunch
2,9.46,No,Lunch
3,9.05,Yes,Dinner
4,6.38,Yes,Dinner
5,9.30,Yes,Lunch
6,1.80,Yes,Dinner
7,2.76,No,Dinner
8,1.41,No,Lunch
9,3.93,Yes,Lunch


In [45]:
df1[['tip','smoker','time']].size

150

**convert pandas series to numpy 1D array using values and to_numpy**

In [48]:
df1[['tip','smoker','time']].to_numpy()

array([[9.73, 'No', 'Dinner'],
       [7.98, 'Yes', 'Lunch'],
       [9.46, 'No', 'Lunch'],
       [9.05, 'Yes', 'Dinner'],
       [6.38, 'Yes', 'Dinner'],
       [9.3, 'Yes', 'Lunch'],
       [1.8, 'Yes', 'Dinner'],
       [2.76, 'No', 'Dinner'],
       [1.41, 'No', 'Lunch'],
       [3.93, 'Yes', 'Lunch'],
       [4.5, 'Yes', 'Dinner'],
       [3.44, 'No', 'Lunch'],
       [8.46, 'Yes', 'Lunch'],
       [4.21, 'Yes', 'Dinner'],
       [3.53, 'Yes', 'Lunch'],
       [5.88, 'No', 'Lunch'],
       [2.27, 'No', 'Dinner'],
       [8.22, 'No', 'Dinner'],
       [1.67, 'Yes', 'Lunch'],
       [9.88, 'Yes', 'Lunch'],
       [7.95, 'No', 'Dinner'],
       [2.79, 'No', 'Dinner'],
       [1.05, 'No', 'Dinner'],
       [8.34, 'No', 'Dinner'],
       [7.36, 'Yes', 'Lunch'],
       [7.56, 'No', 'Dinner'],
       [7.94, 'Yes', 'Dinner'],
       [1.67, 'No', 'Lunch'],
       [4.23, 'Yes', 'Dinner'],
       [2.04, 'No', 'Lunch'],
       [8.77, 'No', 'Dinner'],
       [6.61, 'No', 'Dinner'],
       [3.

In [56]:
df1[['tip','smoker','time']].values

array([[9.73, 'No', 'Dinner'],
       [7.98, 'Yes', 'Lunch'],
       [9.46, 'No', 'Lunch'],
       [9.05, 'Yes', 'Dinner'],
       [6.38, 'Yes', 'Dinner'],
       [9.3, 'Yes', 'Lunch'],
       [1.8, 'Yes', 'Dinner'],
       [2.76, 'No', 'Dinner'],
       [1.41, 'No', 'Lunch'],
       [3.93, 'Yes', 'Lunch'],
       [4.5, 'Yes', 'Dinner'],
       [3.44, 'No', 'Lunch'],
       [8.46, 'Yes', 'Lunch'],
       [4.21, 'Yes', 'Dinner'],
       [3.53, 'Yes', 'Lunch'],
       [5.88, 'No', 'Lunch'],
       [2.27, 'No', 'Dinner'],
       [8.22, 'No', 'Dinner'],
       [1.67, 'Yes', 'Lunch'],
       [9.88, 'Yes', 'Lunch'],
       [7.95, 'No', 'Dinner'],
       [2.79, 'No', 'Dinner'],
       [1.05, 'No', 'Dinner'],
       [8.34, 'No', 'Dinner'],
       [7.36, 'Yes', 'Lunch'],
       [7.56, 'No', 'Dinner'],
       [7.94, 'Yes', 'Dinner'],
       [1.67, 'No', 'Lunch'],
       [4.23, 'Yes', 'Dinner'],
       [2.04, 'No', 'Lunch'],
       [8.77, 'No', 'Dinner'],
       [6.61, 'No', 'Dinner'],
       [3.

**convert pandas dataframe to numpy 2D array**

In [57]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   total_bill     50 non-null     float64
 1   tip            50 non-null     float64
 2   gender         50 non-null     object 
 3   smoker         50 non-null     object 
 4   day            50 non-null     object 
 5   time           50 non-null     object 
 6   no_of_members  50 non-null     int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 2.9+ KB


In [62]:
# check with internet
df1[['day']].to_numpy().ravel()

array(['Thur', 'Thur', 'Sat', 'Fri', 'Fri', 'Thur', 'Sun', 'Fri', 'Sun',
       'Fri', 'Sun', 'Sat', 'Sun', 'Sat', 'Sat', 'Sun', 'Sat', 'Thur',
       'Sat', 'Fri', 'Sun', 'Thur', 'Sun', 'Fri', 'Fri', 'Fri', 'Sat',
       'Sat', 'Sun', 'Sun', 'Thur', 'Thur', 'Sun', 'Sat', 'Fri', 'Sun',
       'Thur', 'Sat', 'Sun', 'Sun', 'Sat', 'Sun', 'Sat', 'Fri', 'Sat',
       'Sat', 'Sat', 'Sun', 'Sun', 'Sat'], dtype=object)

**FILTERING**

In [66]:
# using 1 condition
len(df1[df1['tip']>7])

19

In [72]:
# USING MULTIPLE CONDITIONS
df1[(df1['tip']>7) & (df1['gender']=='Female')]

,total_bill,tip,gender,smoker,day,time,no_of_members
1,47.78,7.98,Female,Yes,Thur,Lunch,3
23,21.49,8.34,Female,No,Fri,Dinner,4
24,25.52,7.36,Female,Yes,Fri,Lunch,1
25,40.33,7.56,Female,No,Fri,Dinner,6
30,32.34,8.77,Female,No,Thur,Dinner,1
36,18.71,7.57,Female,Yes,Thur,Lunch,6
42,6.55,7.85,Female,Yes,Sat,Dinner,6


In [73]:
# find the length using len or shape
len(df1[(df1['tip']>7) & (df1['gender']=='Female')])

7

In [74]:
df1[(df1['tip']>7) & (df1['gender']=='Female')].shape[0]

7

In [77]:
## CROSSTAB
pd.crosstab(df1['gender'], df1['day'])

day,Fri,Sat,Sun,Thur
gender,,,,
Female,6,8,6,4
Male,4,8,10,4


**for discrete values**, **to find unique values**

In [80]:
df1['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [81]:
df1['smoker'].unique()

array(['No', 'Yes'], dtype=object)

In [82]:
df1['gender'].value_counts()

gender
Male      26
Female    24
Name: count, dtype: int64

In [84]:
df1['smoker'].value_counts()

smoker
No     25
Yes    25
Name: count, dtype: int64

In [87]:
df1=df1.rename(columns={'gender':'sex'})
df1

,total_bill,tip,sex,smoker,day,time,no_of_members
0,21.85,9.73,Male,No,Thur,Dinner,4
1,47.78,7.98,Female,Yes,Thur,Lunch,3
2,37.94,9.46,Male,No,Sat,Lunch,1
3,31.94,9.05,Male,Yes,Fri,Dinner,4
4,12.02,6.38,Female,Yes,Fri,Dinner,6
5,12.02,9.30,Male,Yes,Thur,Lunch,4
6,7.61,1.80,Female,Yes,Sun,Dinner,6
7,43.98,2.76,Female,No,Fri,Dinner,3
8,32.05,1.41,Female,No,Sun,Lunch,6
9,36.86,3.93,Male,Yes,Fri,Lunch,1


In [88]:
# again rename to gender from sex
df1=df1.rename(columns={'sex':'gender'})
df1

,total_bill,tip,gender,smoker,day,time,no_of_members
0,21.85,9.73,Male,No,Thur,Dinner,4
1,47.78,7.98,Female,Yes,Thur,Lunch,3
2,37.94,9.46,Male,No,Sat,Lunch,1
3,31.94,9.05,Male,Yes,Fri,Dinner,4
4,12.02,6.38,Female,Yes,Fri,Dinner,6
5,12.02,9.30,Male,Yes,Thur,Lunch,4
6,7.61,1.80,Female,Yes,Sun,Dinner,6
7,43.98,2.76,Female,No,Fri,Dinner,3
8,32.05,1.41,Female,No,Sun,Lunch,6
9,36.86,3.93,Male,Yes,Fri,Lunch,1


**reset display to only limited data**

In [93]:
pd.set_option('display.max_rows', 10)

In [94]:
df1

,total_bill,tip,gender,smoker,day,time,no_of_members
0,21.85,9.73,Male,No,Thur,Dinner,4
1,47.78,7.98,Female,Yes,Thur,Lunch,3
2,37.94,9.46,Male,No,Sat,Lunch,1
3,31.94,9.05,Male,Yes,Fri,Dinner,4
4,12.02,6.38,Female,Yes,Fri,Dinner,6
...,...,...,...,...,...,...,...
45,34.81,5.44,Female,No,Sat,Dinner,2
46,19.03,5.70,Male,No,Sat,Dinner,5
47,28.40,4.85,Male,Yes,Sun,Dinner,6
48,29.60,1.23,Male,Yes,Sun,Dinner,1


In [100]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   total_bill     50 non-null     float64
 1   tip            50 non-null     float64
 2   gender         50 non-null     object 
 3   smoker         50 non-null     object 
 4   day            50 non-null     object 
 5   time           50 non-null     object 
 6   no_of_members  50 non-null     int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 3.1+ KB


**USE OF NUNIQUE TO FIND NO OF UNIQUE VALUES**

In [96]:
df1['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

In [97]:
df1['time'].unique().shape[0]

2

In [104]:
df1['time'].nunique()

2

**USE OF NORMALIZE**

In [112]:
df1['gender'].value_counts(normalize=True)

gender
Male      0.52
Female    0.48
Name: proportion, dtype: float64

**DISCRETIZATION**

In [105]:
df1['total_bill'].min()

5.93

In [106]:
df1['total_bill'].max()

48.65

In [108]:
df1['bill_category']=pd.cut(df1['total_bill'],
                            bins=[0,10,30,50],
                            labels=['low','moderate','good'])

In [111]:
df1['bill_category'].value_counts()

bill_category
moderate    26
good        18
low          6
Name: count, dtype: int64

**GROUPBY**

In [114]:
df1.groupby('gender')['tip'].mean()

gender
Female    4.743333
Male      6.103077
Name: tip, dtype: float64

In [118]:
pd.crosstab(df1['time'],df1['gender'], margins=True)

gender,Female,Male,All
time,,,
Dinner,13,13,26
Lunch,11,13,24
All,24,26,50
